### ISSUE TITLE
Code sandbox example and `github.io/bearing-home` page

### ISSUE THREAD

**Issue by alexanderbrodko** [rosingrind/bearing#19]
We can create a page with live examples hosted with [GitHub Pages](https://pages.github.com/). The page should provide a way to quickly view the library's capabilities and track the current state. The subtasks are planned as following:

- create a website repo as next.js app
- configure next export with `assetPrefix` and `basePath` fixes for css
- set up github actions for deployment
- leave website references at this repo's docs

**Comment by rosingrind** [comment]
According to [docs](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch), it is possible to publish page from branch with such URL as `username.github.io/repository`. Resolution of this issue should follow this guideline and implement `.io` website on a separate `page` branch

**Comment by rosingrind** [comment]
The issue will be closed with #40 as it updates README.md according to changes:
- gh-pages link: https://rosingrind.github.io/bearing-home/
- codesandbox: https://codesandbox.io/s/cool-sea-zmbhw7
